name: pypi-publish

on:
  push:
    branches: ["main","test"]

concurrency:
  group: "pypi-publish"
  cancel-in-progress: false

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
    - name: echo-vars
      run: >
        echo "Github environment: ${{ github.ref_name }}"
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.24"
    - name: Build Python Package
      run: uv build
    - name: Deploy Python Package
      run: uv publish
      env:
        UV_PUBLISH_URL: ${{ vars.UV_PUBLISH_URL }}
        UV_PUBLISH_CHECK_URL: ${{ vars.UV_PUBLISH_CHECK_URL }}
