name: unit-tests
on: [push]
jobs:
  pytest-and-coverage:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.24"
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
        architecture: 'x64'
    - name: Install the project
      run: uv sync --no-dev --group test
    - name: run pytest
      run: uv run pytest --cov-report lcov --cov=xfp tests/ -v
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
    - name: run mypy
      run: uv run mypy src tests
